// RECIPE ACTIONS

export const RECIPE_SEARCH_START = "RECIPE_SEARCH_START";
export const RECIPE_SEARCH_START_MOBILE = "RECIPE_SEARCH_START_MOBILE";
export const RECIPE_SEARCH_SUCCESS_DESKTOP = "RECIPE_SEARCH_SUCCESS_DESKTOP";
export const RECIPE_SEARCH_SUCCESS_MOBILE = "RECIPE_SEARCH_SUCCESS_MOBILE";
export const RECIPE_SEARCH_FAIL_DESKTOP = "RECIPE_SEARCH_FAIL_DESKTOP";
export const RECIPE_SEARCH_FAIL_MOBILE = "RECIPE_SEARCH_FAIL_MOBILE";
export const EXIT_SEARCH_MODAL = "EXIT_SEARCH_MODAL";

// SETTING INTERSECTION OBSERVER FOR HEADER IN RECIPE ACTION

// RECIPELIST ACTIONS

export const RECIPELIST_PAGE_INCREMENT = "RECIPELIST_PAGE_INCREMENT";
export const RECIPELIST_PAGE_DECREMENT = "RECIPELIST_PAGE_DECREMENT";
export const RECIPELIST_SEARCH_SUMMARY_START =
  "RECIPELIST_SEARCH_SUMMARY_START";
export const RECIPELIST_SEARCH_SUMMARY_SUCCESS =
  "RECIPELIST_SEARCH_SUMMARY_SUCCESS";
export const RECIPELIST_SEARCH_SUMMARY_FAIL = "RECIPELIST_SEARCH_SUMMARY_FAIL";
export const PAGE_INCREMENT = "PAGE_INCREMENT";
export const PAGE_DECREMENT = "PAGE_DECREMENT";

// LOGIN/SIGNUP ACTIONS

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
export const AUTH_INIT = "AUTH_INIT";
export const AUTH_RESET_ERROR = "AUTH_RESET_ERROR";

// BOOKMARK AND MY-RECIPE ACIONS

export const RECIPE_ADD_TO_BOOKMARK = "RECIPE_ADD_TO_BOOKMARK";
export const RECIPE_REMOVE_FROM_BOOKMARK = "RECIPE_REMOVE_FROM_BOOKMARK";
export const RECIPE_TOGGLE_IS_BOOKMARKED = "RECIPE_TOGGLE_IS_BOOKMARKED";
export const RECIPE_INIT_IS_BOOKMARKED = "RECIPE_INIT_IS_BOOKMARKED";
export const RECIPE_UPDATE_BOOKMARK_ON_RELOAD =
  "RECIPE_UPDATE_BOOKMARK_ON_RELOAD";
export const RECIPE_SET_SUMMARY_FOR_BOOKMARK =
  "RECIPE_SET_SUMMARY_FOR_BOOKMARK";
export const RECIPE_REMOVE_SUMMARY = "RECIPE_REMOVE_SUMMARY";
export const RECIPE_ADD_SUMMARY = "RECIPE_ADD_SUMMARY";
export const RECIPE_ADD_TO_MY_RECIPE = "RECIPE_ADD_TO_MY_RECIPE";
export const RECIPE_REMOVE_FROM_MY_RECIPE = "RECIPE_REMOVE_FROM_MY_RECIPE";
